### ISSUE TITLE
Target info UI cuts off icons

### ISSUE THREAD

**Issue by ascobolonline** [NotNite/DeeperDeepDungeonDex#3]
Is it possible to make the upper part of the target info UI bit higher or even resizable, as for me it cuts off the status icons of the targeted  monster.
![image](https://github.com/user-attachments/assets/881b0577-47b2-4b09-98f5-43448409dff1)

**Comment by MKhayle** [comment]
This is a Dalamud Style issue ; you can either scroll down or adjust your Dalamud Style (`/xlsettings` -> Appearance -> Style Editor) so that it displays correctly.

**Comment by ascobolonline** [comment]
Thanks, that worked.

**Comment by ascobolonline** [comment]
Can be closed ^^
